export const GET_REPORT_LIST = 'REPORTLIST/GET_REPORT_LIST' as const;
export const GET_REPORT_LIST_SUCCESS = 'REPORTLIST/GET_REPORT_LIST_SUCCESS' as const;
export const GET_REPORT_LIST_FAILURE = 'REPORTLIST/GET_REPORT_LIST_FAILURE' as const;
export const PAGE = 'REPORTLIST/PAGE' as const;