export const OLD_PASSWORD = 'CHANGE_PASSWORD/OLD_PASSWORD' as const;
export const NEW_PASSWORD = 'CHANGE_PASSWORD/NEW_PASSWORD' as const;
export const CHECK_PASSWORD = 'CHANGE_PASSWORD/CHECK_PASSWORD' as const;
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD/CHANGE_PASSWORD' as const;
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD/CHANGE_PASSWORD_SUCCESS' as const;
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD/CHANGE_PASSWORD_FAILURE' as const;
export const IS_CHANGE_PASSWORD = 'CHANGE_PASSWORD/IS_CHANGE_PASSWORD' as const;