export const GET_SEARCH_PROJECT = 'SEARCH_PROJECT/GET_SEARCH_PROJECT' as const;
export const GET_SEARCH_PROJECT_SUCCESS = 'SEARCH_PROJECT/GET_SEARCH_PROJECT_SUCCESS' as const;
export const GET_SEARCH_PROJECT_FAILURE = 'SEARCH_PROJECT/GET_SEARCH_PROJECT_FAILURE' as const;
export const PAGE = 'SEARCHP_ROJECT/PAGE' as const;
export const SEARCHING = 'SEARCH_PROJECT/SEARCHING' as const;