export const GET_SEARCH_PROJECT = 'SEARCH_PROJECT/GET_SEARCH_PROJECT' as const;
export const GET_SEARCH_PROJECT_SUCCESS = 'SEARCH_PROJECT/GET_SEARCH_PROJECT_SUCCESS' as const;
export const GET_SEARCH_PROJECT_FAILURE = 'SEARCH_PROJECT/GET_SEARCH_PROJECT_FAILURE' as const;

export const QUERY = 'SEARCH_PROJECT/QUERY' as const;
export const PAGE = 'SEARCH_PROJECT/PAGE' as const;