export const GET_VIEW_PROJECT = 'VIEW/GET_VIEW_PROJECT' as const;
export const GET_VIEW_PROJECT_SUCCESS = 'VIEW/GET_VIEW_PROJECT_SUCCESS' as const;
export const GET_VIEW_PROJECT_FAILURE = 'VIEW/GET_VIEW_PROJECT_FAILURE' as const;

export const FIELD = 'VIEW/FIELD' as const;
export const PAGE = 'VIEW/PAGE' as const;

export const CURRENT_PROJECT_ID = 'VIEW/CURRENT_PROJECT_ID' as const;
export const CURRENT_PROJECT_TITLE = 'VIEW/CURRENT_PROJECT_TITLE' as const;
export const CURRENT_PROJECT_GIT_URL = 'VIEW/CURRENT_PROJECT_GIT_URL' as const;
export const CURRENT_PROJECT_SERVICE_URL = 'VIEW/CURRENT_PROJECT_SERVICE_URL' as const;
export const CURRENT_PROJECT_DOCS_URL = 'VIEW/CURRENT_PROJECT_DOCS_URL' as const;