export const GET_VIEW_PROJECT = 'VIEW/GET_VIEW_PROJECT' as const;
export const GET_VIEW_PROJECT_SUCCESS = 'VIEW/GET_VIEW_PROJECT_SUCCESS' as const;
export const GET_VIEW_PROJECT_FAILURE = 'VIEW/GET_VIEW_PROJECT_FAILURE' as const;

export const FIELD = 'VIEW/FIELD' as const;
export const PAGE = 'VIEW/PAGE' as const;
export const CURRENTPROJECTID = 'VIEW/CURRENTPROJECTID' as const;
export const CURRENTPROJECTTITLE = 'VIEW/CURRENTPROJECTTITLE' as const;
export const CURRENTPROJECT_GIT_URL = 'VIEW/CURRENTPROJECT_GIT_URL' as const;
export const CURRENTPROJECT_SERVICE_URL = 'VIEW/CURRENTPROJECT_SERVICEURL' as const;
export const CURRENTPROJECT_DOCS_URL = 'VIEW/CURRENTPROJECT_DOCS_URL' as const;